export const regionsQuery = (query) => {
  switch (query.toLowerCase()) {
    case "крим":
    case "автономна республіка крим":
    case "севастополь":
    case "сімферополь":
      return "Crimea";
    case "черкаська":
    case "черкаси":
      return "Cherkasy";
    case "чернігівська":
    case "чернігів":
      return "Chernihiv";
    case "чернівецька":
    case "чернівці":
      return "Chernivtsi";
    case "дніпропетровська":
    case "дніпро":
      return "Dnipropetrovsk";
    case "донецька":
    case "донецьк":
      return "Donetsk";
    case "івано-франківська":
    case "івано-франківськ":
      return "Ivano-Frankivsk";
    case "харківська":
    case "харків":
      return "Kharkiv";
    case "херсонська":
    case "херсон":
      return "Kherson";
    case "хмельницька":
    case "хмельницький":
      return "Khmelnytskyi";
    case "київська":
    case "київ":
      return "Kiev";
    case "кіровоградська":
    case "кропивницький":
      return "Kirovohrad";
    case "луганська":
    case "луганськ":
      return "Luhansk";
    case "львівська":
    case "львів":
      return "Lviv";
    case "миколаївська":
    case "миколаїв":
      return "Mykolaiv";
    case "одеська":
    case "одеса":
      return "Odessa";
    case "полтавська":
    case "полтава":
      return "Poltava";
    case "рівненська":
    case "рівне":
      return "Rivne";
    case "сумська":
    case "суми":
      return "Sumu";
    case "тернопільська":
    case "тернопіль":
      return "Ternopil";
    case "закарпатська":
    case "ужгород":
      return "Zakarpattia";
    case "вінницька":
    case "вінниця":
      return "Vinnytsia";
    case "волинська":
    case "луцьк":
      return "Volyn";
    case "запорізька":
    case "запоріжжя":
      return "Zaporizhia";
    case "житомирська":
    case "житомир":
      return "Zhytomyr";
    default:
      return "";
  }
};
